### ISSUE TITLE
Feature request: support Workbook options in XLSXWriter.open()

### ISSUE THREAD

**Issue by bdeeney** [pyexcel/pyexcel-xlsxw#1]
The [xlsxwriter.workbook.Workbook](http://xlsxwriter.readthedocs.io/workbook.html#Workbook) constructor defines an 'options' kwarg that accepts a _dict_ of workbook settings, e.g.:

```python
options = {'constant_memory': True, 'strings_to_numbers': True}
workbook = xlsxwriter.Workbook(filename, options=options)
```

This is a request to add pass-through support for the 'options' kwarg to [XLSXWriter.open()](https://github.com/pyexcel/pyexcel-xlsxw/blob/master/pyexcel_xlsxw/xlsx.py#L39):

```python
options = {'constant_memory': True, 'strings_to_numbers': True}
writer = pyexcel_xlsxw.xlsx.XLSXWriter()
writer.open(filename, options=options)
```

**Comment by chfw** [comment]
Yes, the parameters should have been passed.
